title:              Neural Nexus
email:              mdirfan5702@gmail.com
description:        Data Science, AI tips and tricks
author:             Neural Nexus
baseurl:            "/Neural-Nexus"
url:                "https://dev-mdirfan.github.io"
# https://dev-mdirfan.github.io/Neural-Nexus/
# https://neuralnexus.github.io

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

highlighter: rouge
